- conf/bafu.conf.part
These 4 layers should go on prod on 7th january
> Config for new BAFU layer (aulav)

- conf/uvek.conf.part
This common pr should be updated by the data integrators for the next deploy.
> index updates for next deploy 20150106

- conf/bod.conf.part
- conf/search.conf.part
- conf/wordforms_de.txt
- conf/wordforms_it.txt
- conf/wordforms_main.txt
Should solve #184 if old files are cleared.
> Replacing multiple wordforms with only one file

- conf/wordforms_main.txt
Removed traductions (not efficient because chaining is not possible)
Add ZI and GI, + new logic to enable user mistakes
> Wordforms upgrade

- conf/uvek.conf.part
> Add layer ch.bfe.windenergielayer

- conf/uvek.conf.part
By user request, several BFE layers are switched from only queryable to searchable.
Please merge if OK
> switched several BFE indexes to searchable

- conf/bafu.conf.part
- conf/bod.conf.part
- conf/db.conf.in
- conf/dritte.conf.part
- conf/kogis.conf.part
- conf/lubis.conf.part
- conf/search.conf.part
- conf/stopo.conf.part
- conf/uvek.conf.part
- conf/vbs.conf.part
- deploy/deploy-conf-only.cfg
- deploy/deploy-conf-only.sh
- deploy/deploy.cfg
- deploy/hooks/post-restore-code
- deploy/hooks_conf_only/post-restore-code
- deploy/pg2sphinx_trigger.py
This pr has to be merged after the switch to the new db streaming replication infra.
> Dev ltclm streaming replication

- conf/bafu.conf.part
Link with chsdi https://github.com/geoadmin/mf-chsdi3/pull/1501
> Set config for new bafu layer

- conf/bafu.conf.part
merged the last GEWISS batch. Thanks @pfanguin and @daguer !
> Data sphinx bafu gewiss

- conf/stopo.conf.part
split gisgeol layer ch.swisstopo.geologie-gisgeol-flaechen-10to21000km2 into
ch.swisstopo.geologie-gisgeol-flaechen-1000to21000km2
ch.swisstopo.geologie-gisgeol-flaechen-100to1000km2
ch.swisstopo.geologie-gisgeol-flaechen-10to100km2
> split gisgeol layer

- conf/bafu.conf.part
> Use correct column

- conf/search.conf.part
This one should be merged for the new swisssearch origin gazetteer. 
See https://github.com/geoadmin/mf-chsdi3/issues/1495
> Dev ltclm swisssearch swissnames3d

- conf/lubis.conf.part
will be used for https://github.com/geoadmin/mf-chsdi3/pull/1636
> new index for ch.swisstopo.lubis-luftbilder_schraegaufnahmen

- conf/uvek.conf.part
index for layers
* ch.astra.wanderland
* ch.astra.veloland
* ch.astra.skatingland
* ch.astra.mountainbikeland
> index chmobil layers

- conf/uvek.conf.part
See : https://github.com/geoadmin/mf-chsdi3/pull/1684
> Sphinx index for oev

- conf/search.conf.part
the new haltestellen index is currently available on dev
dave will ask the data owner for the translation of the new categories. For now we will keep them in german.
> replace swissnames3d haltestellen with bav haltestellen

- conf/bafu.conf.part
@daguer can you please review? Thank you
> add sphynx index auen vegetationskarte

- conf/stopo.conf.part
@ltclm Thank you for your help, I added the row_number and indeed it works fine now! If you are bored before the holidays, could you have a look please? Thanks!
> add search index for shop layers

- conf/stopo.conf.part
@rfrancel  i have removed this index because the query is not working.
> remove wkt33 due to query which is not working

- conf/stopo.conf.part
@ltclm yes I had to correct the indices for the shop layers, strange that it showed no problem for the other ones.. Here is a PR with all the indices for all shop layers.
If you can review this, it would be very nice. Thanks
> shop layers indices

- conf/bafu.conf.part
Link with https://github.com/geoadmin/mf-chsdi3/pull/1898
> Update conf because attribute was removed in source table

- conf/uvek.conf.part
this will activate the feature search on ch.bazl.luftfahrthindernis
> activate luftfahrthindernis feature search

- conf/bafu.conf.part
@pfanguin Can you check that this is correct?
I removed some fields as they are not in DB anymore.
> Remove missing fields

- conf/stopo.conf.part
@ltclm thank you for noticing my bad configuration. Here is a PR with the indices for next deploy for the two layers. Thank you for merging if it is ok.
> add indices for shop layers skitouren and grav atlas

- conf/search.conf.part
this will remove the soundex index as discussed in https://github.com/geoadmin/service-sphinxsearch/issues/244
> remove soundex fuzzy index

- Makefile
@gjn If I'm not mistaken, this has to be removed. Thank you for checking if I'm right.
> remove sn25 from makefile

- conf/stopo.conf.part
@gjn Here is a PR for 6 fertig shop products. Thank you for reviewing
> add sphinx index for fertigprodukte

- conf/bafu.conf.part
https://github.com/geoadmin/mf-chsdi3/pull/2042
> sphinx index paerke

- conf/vbs.conf.part
> Add new attribute for vbs

- conf/search.conf.part
This reverts https://github.com/geoadmin/service-sphinxsearch/pull/275
@ltclm As discussed, I'll revert the POC PR for this weeks deploy.
I'll merge and update the search on dev main.
> Revert back to old gazetteer

- conf/search.conf.part
Will fix the query from https://github.com/geoadmin/service-sphinxsearch/pull/277
The query has been broken by a rebase which went wrong.
> fix query which has been broken by rebase

- conf/evd.conf.part
Do not replace '-' by '_' for the layer name
> Fix layer name typo

- conf/uvek.conf.part
sphinx search is created for ch.bfe.bikesharing
> sphinx for bikesharing

- conf/vbs.conf.part
Sphinx search created for this layer.
> sphinx created for ch.vbs.waldschadenkarte

- conf/stopo.conf.part
I am rebuilding indices in dev.
Link to https://github.com/geoadmin/mf-chsdi3/pull/2267
> Shop renaming of layer id

- deploy/pg2sphinx_trigger.py
pattern
on error the scan continues
> do a graceful explain verbose on all queries matching the database

- conf/uvek.conf.part
Remove config of ivs-reg_loc_sub
https://github.com/geoadmin/mf-chsdi3/issues/2274
> Decomissionin ch.astra.ivs-reg_loc.sub and ch.kantone.ivs-reg_loc

- Makefile
- scripts/pre-commit.sh
``make template`` will install a pre-commit hook into .git/hooks/
the hook will check:
* sphinx configuration with indextool
* index queries with explain verbose
> install pre-commit hook

- conf/stopo.conf.part
see : https://github.com/geoadmin/mf-chsdi3/issues/2273
> Decommission of old shop layers

- conf/search.conf.part
triggered by https://github.com/geoadmin/mf-chsdi3/issues/2317#issuecomment-259606920
> intersect plz polygon geometry with canton geometry

- conf/dritte.conf.part
@ltclm Cound you have a look before merging? [try](https://mf-geoadmin3.dev.bgdi.ch/src/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltrea&wms_url=%2F%2Fwms-bod.dev.bgdi.ch%2Fltrea&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.astra.wanderland,ch.mobility.standorte&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=199408.95&Y=602921.79&zoom=10&catalogNodes=687,720) f. ex. ID 3765
> ch.mobility.standorte

- conf/search.conf.part
- deploy/pg2sphinx_trigger.py
[TEST](https://mf-geoadmin3.dev.bgdi.ch/)
thanks @ltclm for the regexp
**This PR adds the commune name to the search field.**
@davidoesch Let me know if you're happy with the ranking.
I'm trying to search for the following location:
Hauptgipfel Stelli (GR) - Arosa
While this works on https://map.geo.admin.ch with the search term "stelli", I couldn't get it working with the SearchServer REST API:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&amp;lang=de&amp;returnGeometry=true&amp;origins=gazetteer&amp;searchText=stelli
First of all, it only returns 30 results despite the (default) limit of 50.
Additionally, the result set never contains "Hauptgipfel Stelli (GR) - Arosa". Maybe someone has an idea how the search has to look like to get the desired result?
I was …
> Communes gazetter

- conf/search.conf.part
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/?swisssearch=2108)
> use label position from data

- conf/stopo.conf.part
@loicgasser Please merge me, thank you. Chsdi is already merged.
> added sphinx index for tiefengeothermie

- conf/bafu.conf.part
- conf/dritte.conf.part
> Ltrea update waldreservate

- conf/bafu.conf.part
[try](https://mf-chsdi3.dev.bgdi.ch/ltrea_hunde/shorten/72f8c019c4)
> herdenschutzhunde

- conf/bafu.conf.part
Use table update for the moment because table structure has changed
> Add config for layer c.bafu.bundesinventare-bln

- conf/uvek.conf.part
@loicgasser Decomissioned layers removed from sphinx
> removed layer ch.bav.laerm-emissionsplan_eisenbahn{tag,nacht}

- conf/search.conf.part
- conf/wordforms_main.txt
infix for detail_de, detail_fr etc.. should be one
> Zipcode preview

- conf/kogis.conf.part
- conf/search.conf.part
According to discussions with BFS.
> Search lang in feature search not location search

- conf/stopo.conf.part
New layer is: ch.swisstopo.geologie-geologischer_atlas_vector.metadata
> New config for an stopo layer 

- conf/bafu.conf.part
Tested with `service-sphinxsearch/test/test.py`
Deployment date: 06.12.17
> Sphinx indices for ch.bafu.bundesinventare-*

- conf/bafu.conf.part
ping @nadine-piveteau for next time 
Process to develop sphinx search goes as follow:
1. Create the config in `config/*.part.conf``
2. `make template`
3.  `sudo su sphinxsearch`
4. `make move-template` -> will check the config, and test all SQL queries. If this test passes then you can create a PR.
I don't know if this is documented in the wiki, if not please complete it. Thanks!
> Remove duplicate

- conf/uvek.conf.part
Layer concenerned:
ch.bakom.notruf-112_festnetz
ch.bakom.notruf-112_mobilnetz
ch.bakom.notruf-112_satellit
ch.bakom.notruf-117_festnetz
ch.bakom.notruf-117_mobilnetz
ch.bakom.notruf-118_festnetz
ch.bakom.notruf-118_mobilnetz
ch.bakom.notruf-143_festnetz
ch.bakom.notruf-143_mobilnetz
ch.bakom.notruf-144_festnetz
ch.bakom.notruf-144_mobilnetz
ch.bakom.notruf-147_festnetz
ch.bakom.notruf-147_mobilnetz
ch.bakom.notruf
Request in Jira (27.06.2018 14:09) https://jira.swisstopo.ch/browse/BGDIDI_KB-2138
> make bakom festnetz searchable

- conf/uvek.conf.part
Reverts geoadmin/service-sphinxsearch#383
> Revert "[Don't Merge]Update sphinx config for ch.bfe.sachplan-geologie-tiefenlager"

- conf/bafu.conf.part
should be considered for the deploy on 27.2.2019
> added index for ch_bafu_auen_ausserhalb_bundesinventar

- conf/stopo.conf.part
@ltclm please DO NOT MERGE today, the test link does not work, I have to find why... Thank you :-)
[test link](https://mf-chsdi3.dev.bgdi.ch/brg_gewaessernetz/shorten/81097c713f)
> add conf for gewaessernetz_referenz

- conf/uvek.conf.part
The tables will be removed after the deploy
> Remove config for sachplan-geologie-tiefenlager_vernehmlassung

- conf/search.conf.part
[Testlink api](https://mf-chsdi3.dev.bgdi.ch/1908071243/rest/services/ech/SearchServer?sr=2056&searchText=9000&lang=de&type=locations)
[Testlink viewer](https://mf-geoadmin3.dev.bgdi.ch/index.html?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch)
fixes wrong coordinate issue,
> plz coord attributes are lv95 now

- conf/bafu.conf.part
test.py on this index is successful
> add sphinx index

- conf/bafu.conf.part
> update teileinzugsgebiete_2 index

- conf/bafu.conf.part
Tests with python script are ok!
>  hydromessstationen add indexes

- conf/stopo.conf.part
https://jira.swisstopo.ch/browse/BGDIDI_KB-1335
> remove layer ch.swisstopo.geologie-generalkarte-ggk200_papier.metadata

- conf/stopo.conf.part
[testlink](https://mf-chsdi3.dev.bgdi.ch/feature_amtliche_addressen/shorten/89202c67ed)
> add index for ch.swisstopo.amtliches-gebaeudeadressverzeichnis

- conf/bafu.conf.part
[testlink](https://mf-chsdi3.dev.bgdi.ch/ltbal_auen/shorten/8a0c438af9)
> new query / table for ch.bafu.auen-vegetationskarten

- conf/edi.conf.part
- conf/kogis.conf.part
- conf/search.conf.part
new data  source for swisssearch and feature search
indexes have been updated on dev -> [testlink](https://mf-chsdi3.dev.bgdi.ch/shorten/8b129683e9)
> initial import new sedex based data structure for bfs address data

- conf/edi.conf.part
- conf/kogis.conf.part
- conf/search.conf.part
we will have to revert this pr once the final decision has been taken
> revert sedex gwr

- conf/edi.conf.part
- conf/kogis.conf.part
- conf/search.conf.part
Reverts geoadmin/service-sphinxsearch#437
> activate sedex gwr

- conf/vbs.conf.part
Added attributes for the new table structure
> Add search attributes

- conf/uvek.conf.part
https://mf-chsdi3.dev.bgdi.ch/ltmbr_add_seilbahnen_bundeskonzession/shorten/8c48b773fe
> ltmbr add seilbahnen bundeskonzession

- conf/search.conf.part
there is a wrong html tag in the label of swisssearch results
we have to fix that ASAP
> fix wrong html tag

- conf/stopo.conf.part
https://mf-chsdi3.dev.bgdi.ch/ltmbr_gletscherausdehnung_BGDIDIC-1924/shorten/8d26742d66
> ltmbr gletscherausdehnung BGDIDIC-1924

- conf/stopo.conf.part
> remove geocover index

- conf/stopo.conf.part
ch.swisstopo.geologie-geotechnik-ziegeleien_1965
ch.swisstopo.geologie-geotechnik-ziegeleien_1995
https://jira.swisstopo.ch/browse/BGDIDIC-1960
https://jira.swisstopo.ch/browse/BGDIDIC-1961
> remove deprecated snippets

- conf/uvek.conf.part
This updates only the table to use as there is a new table for this layer.
> ltmbr update erneuerbarheizen

- deploy/hooks_conf_only/post-restore
- deploy/hooks_conf_only/post-restore-code
fix /tmp/np issue with default hook
service start with custom function
> some improvements in the deploy script

- conf/uvek.conf.part
This reverts commit a5e9605e8db24d8b4c3d99333e13008704672618.
> Revert "Add ch.bfe.waermepotential-gewaesser"

- deploy/pg2sphinx_trigger.py
has to be deployed before changing the db deploy script. https://github.com/geoadmin/deploy/pull/52
> BGDIINF_SB-1967 allow comma separated list of index or database pattern

- conf/uvek.conf.part
[testlink](https://s.geo.admin.ch/651749081570)
> Data bgdidid 1457 obstacles

- conf/uvek.conf.part
add new index for bazl.luftfahrthindernis-aenderungen
rename layer
> BGDIDID-1457: update index bazl.luftfahrthindernis

- conf/stopo.conf.part
more layers to be removed after the ddl of https://github.com/geoadmin/tool-wms/pull/195
> BGDIINF_SB-2388: remove deprecated layers

- conf/search.conf.part
this pr will add a new attribute with the tlm objektklasse to the swisssearch distributed index.
> BGDIINF_SB-2331: add tlm objektklasse to return payload

- conf/search.conf.part
- conf/stopo.conf.part
- conf/uvek.conf.part
this will update the develop-docker branch with the latest changes from master
> Update develop docker

- README.md
- conf/kogis.conf.part
- conf/stopo.conf.part
- conf/uvek.conf.part
with the latest rds snapshot in Frankfurt, this will merge the latest changes of master branch
> Feature update develop docker

- .github/workflows/create-milestone.yml
- .github/workflows/milestone-version.yml
- .github/workflows/pr-auto-milestone.yml
See https://github.com/geoadmin/.github/pull/24
> Setup requirements for milestone branch protection and auto deletion

- Makefile
> remove warning on docker login

- Dockerfile
- scripts/checker.sh
the current master image does not have all the liveness probe changes.
this will update the master branch with develop-2022-09-07.
> Fix update liveness probe

- conf/stopo.conf.part
[testlink](https://github.com/geoadmin/service-sphinxsearch/pull/504)
> BGDIDIC-1792: add nummer to index

- scripts/docker-cmd.sh
not yet present in the efs.
This auto-create will fail during deploy because new sphinx config will
be deployed before the database deploy.
> fix docker-cmd script, do not create index on container start which are

- scripts/checker.sh
- scripts/docker-cmd.sh
- scripts/docker-entry.sh
* readiness probe, status will be written to checker_ready.txt in shared volume or
tmp folder
TODO:
> BGDIINF_SB-2530: add a first draft of readiness probe

- Dockerfile
- scripts/checker.sh
- scripts/docker-cmd.sh
- scripts/docker-crontab
- scripts/docker-entry.sh
as proposed in our guidelines docker best practices we dont wan to run containers as root user
the user will be switched in the dockerfile
simplify readiness probe/check
> run container as non root user geodata

- conf/uvek.conf.part
> BGDIDIC-2523: add new layer ch.bazl.luftfahrthindernis-klein

- conf/uvek.conf.part
config for:
- BGDIDIC-2712 in kraft
- BGDIDIC-2713 in anhoerung
> BGDIDIC-2709 add search config for:

- scripts/index-sync-rotate.sh
Added new observability fields to json log formatter. Old fields to be removed after decommission of old logging solution.
> PB-428: Updated json logging format
