geoadmin/service-search-sphinx

deploy/deploy-conf-only.sh

since the code section has been disabled when trying to ``make deploy-int-clean_index``, the post-restore-code hook has never been executed on the deploy target. the code section should be kept active. the post-restore-code hook is not copying files if executed in clean_index mode.

fix clean_index bug

---

conf/db.conf.in

As discussed in 4220590e87402f5f0d6030f0c870ef0c8b9c00fe
this will simplify the config for multilanguage support and get rid of warnings when generating indices

add inherited source template to supporting translated labels

---

conf/wordforms_main.txt

Requires an update of swisssearch indices when deploying.
Fix #203

Remove circular references on wordforms

---

conf/search.conf.part

Since we have lines and polygons now, we cant provide commune and canton information anymore.

remove debug information from swisssearch_preview swissnames3d index

---

conf/db.conf.in

sphinx should use the dedicated sandbox instance for index creation

use pg-sandbox.bgdi.ch for sphinx index creation

---

conf/stopo.conf.part

The name of the index was not correct, as it didn't correspond to the layer name as specified in the bod. Therefore, the search on this layer did not work. See https://jenkins.ci.bgdi.ch/job/chsdi3/289/console
@daguer Please test the search after you create the index.

Fix name of geometa layer

---

conf/bod.conf.part

This is for https://github.com/geoadmin/mf-chsdi3/issues/1709
We need to add a separated field if we want to give a higher weight to the title info.
@ltclm `kurzbezeichnung` could be removed from the `volltextsuche` as it is now redundant.

Add title field

---

deploy/move-template.sh

We should merge this asap.
This will prevent that buggy queries, which are passing the built-in syntax checker are blocking the db deploy trigger.
Actually the db trigger will not work anymore if
* one of the sphinx queries of a database is not working
* a table deploy of this database is launching the db trigger 
We should merge this asap.

this will improve the valdiation of the new config before moving it to

---

conf/search.conf.part

NOT TO BE DEPLOYED BEFORE END OF FEBRUARY
This removes the sn25 based indices from swissearch distributed indices.
In a second step (when front-ends are adapted), we can remove the distributed preview indices.

Remove sn25 indices from swisssearch

---

conf/search.conf.part

the new query is merging swissnames3d data with lk10 data for swisssearch gazetteer
This new query has to be published at the same time as the new lk10 layer

[WIP] new query for swisssearch gazetteer

---

conf/evd.conf.part

Create index config for layer blw.klimaeignung and blw.bodeneignung
Rq : each layer ch.blw.klimaeignung* use the same table (blw.klimaeignung) the same for layer ch.blw.bodeneignung (blw.bodeneignung)
Tests 
python test/test.py -i ch_blw_klimaeignung_typ -e 'Futterbau'
python test/test.py -i ch_blw_klimaeignung_koernermais -e 'Futterbau'
python test/test.py -i ch_blw_klimaeignung_spezialkulturen -e 'Futterbau'
python test/test.py -i ch_blw_klimaeignung_zwischenfruchtbau -e 'Futterbau'
python test/test.py -i ch_blw_klimaeignung_kartoffeln -e 'Futterbau'
python test/test.py -i ch_blw_klimaeignung_getreidebau -e 'Futterbau'
python test/test.py -i ch_blw_klimaeignung_futterbau -e 'Futterbau'
python test/test.py -i ch_blw_klimaeignung_kulturland -e 'Futterbau'
python test/test.py -i …

Add new config for db evd. 

---

conf/search.conf.part

this pr will add a new rank for haltestellen within the gazetteer index.
This will allow us to do a better ranking of the gazetteer results.
the affected indices can be build with:
```bash
$ time indexer --verbose --rotate --sighup-each --config conf/sphinx.conf address address_metaphone haltestellen haltestellen_metaphone
```
the rank has been changed from
| rank | source    |
|------|-----------|
| 1    | zipcode   |
| 2    | gg25      |
| 3    | district  |
| 4    | kanton    |
| 5    | gazetteer (swissnames,dkm10,haltestellen) |
| 6    | address   |
| 7    | not used  |
| 8    | not used  |
| 9    | not used  |
| 10   | parcel    |
to
| rank | source    |
|------|-----------|
| 1    | zipcode   |
| 2    | gg25      |
| 3    | district  |
| 4    | kanton    |
| 5    | gazetteer …

add new ranking for gazetteer.haltestellen

---

conf/uvek.conf.part

@simonevonheute we had to change the sphinx query because the table structure has been changed.

fix bikeshare query

---

conf/stopo.conf.part

ID is too for this layer and source was not defined.
It's one rectangle so I propose to remove it. There is really nothing else we can do unless we change the id as index names must have exactly the same name as the bodId (minus the `replace('.', '_')`)

Remove unreferenced index

---

conf/stopo.conf.part

[Chsdi : #2314](https://github.com/geoadmin/mf-chsdi3/pull/2314)
- ch.swisstopo.wanderkarte50_papier.metadata
(old ch.swisstopo.wk50-papierkarte.metadata)
- ch.swisstopo.landeskarte50_papier.metadata
(old ch.swisstopo.lk50-papierkarte.metadata)
- ch.swisstopo.landeskarte25_papier.metadata
(old ch.swisstopo.lk25-papierkarte.metadata)
- ch.swisstopo.luftfahrtkarten-icao_papier.metadata
(old ch.swisstopo.icao-papierkarte.metadata)
- ch.swisstopo.landeskarte100_papier.metadata
(old ch.swisstopo.lk100-papierkarte.metadata)

Add new layers for regrouping shop

---

conf/uvek.conf.part

More attributes in search, as more are being displayed in [tooltip](https://mf-geoadmin3.dev.bgdi.ch/?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltrea_bav_eisenbahn_strecke&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.bav.schienennetz&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=215750.00&Y=644000.00&zoom=5).

update search for bav.schienen_*

---

conf/search.conf.part

This pr adds a new attribute to the following partial indices of swissearch:
address -> zoomlevel 10  [1]
parcel -> zoomlevel 10  [1]
swissnames3d/gazetteer -> zoomlevel 9 for everything except dkm, zoomlevel 10 for dkm [2]
How will we treat the swisssearch indices without this zoomlevel information?
zoomlevel = NULL
no zoomlevel attribute (see this pr)
zoomlevel = 0
[1] https://github.com/geoadmin/mf-geoadmin3/blob/febce145bef4d99956132a3a6ac6371fd5c848c8/src/components/search/SearchTypesDirectives.js#L16
[2] https://github.com/geoadmin/mf-geoadmin3/issues/3394

add zoomlevel attribute to some swisssearch indices

---

conf/db.conf.in

can be offline for 1 hour or more, that's why we are using the
production elb now for sphinx queries

pg-sandbox.bgdi.ch elb will not be stable anymore, snapshotter instance

---

conf/stopo.conf.part

ping @ltclm 
Because we'll never use these indices and project is dead, we removed the table and view containing this data.
See: https://github.com/geoadmin/tool-wms/pull/52

Remove old test indices historische namen

---

conf/search.conf.part

Fix for https://github.com/geoadmin/service-sphinxsearch/issues/323
OLD
- 'zipcode': 1
- 'gg25': 2
- 'district': 3
- 'kantone': 4
- 'gazetteer': 5
- 'address': 6
- 'hatestellen': 7
- 'parcel': 10
NEW
- 'zipcode': 1
- 'gg25': 2
- 'district': 3
- 'kantone': 4
- 'gazetteer (ort)': 5
- 'gazetteer': 6
- 'address': 7
- 'hatestellen': 8
- 'parcel': 10
[Test link API](https://mf-chsdi3.dev.bgdi.ch/gal_search_rank/rest/services/ech/SearchServer?searchText=gstaad%20saanen&type=locations&origins=gazetteer)
[Test link geoadmin dev](https://mf-chsdi3.dev.bgdi.ch/gal_search_rank/shorten/7172dcb910)

Rank ORT higher

---

conf/search.conf.part

that's why we have to hide duplicates in the query
fixes https://github.com/geoadmin/mf-geoadmin3/issues/3941
Index has been updated on dev [environment](https://mf-geoadmin3.dev.bgdi.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,)
search for 
```
schliern
biancograt
igl crap
kw fiesch
albumo apriasca
```

tlm.dkm_search has prioriy over tlm.swissnames_* 

---

conf/bafu.conf.part

@daguer : when I built the indices, there was a query error concerning the layer `ch.bafu.typisierung-fliessgewaesser` you integrated few months ago. I fixed it, but could you just check if you agree with the modifications?

sphinx index for ch.bafu.bundesinventare-auen_vegetation_alpin

---

conf/db.conf.in
deploy/deploy.cfg
deploy/hooks/post-restore-code

we have to patch the db deploy script too before merging this one.
db deploy script fires a dml trigger which is updating sphinx indices.
the db deploy script is currently waiting for a constistent replication state of the slaves behind pg.bgdi.ch.
We have to wait for the pg-sandbox slaves for dev and int table deploy.

reorder db usage

---

conf/search.conf.part

based on the discussion https://github.com/geoadmin/mf-chsdi3/issues/3007
this will replace the source of canton information in plz search results
spatial intersection will be replaced with attribute (data.geo.admin.ch > CSV)
Testlink:
https://mf-chsdi3.dev.bgdi.ch/shorten/7dfec2d7e6

use canton information from data

---

conf/search.conf.part

old sphinx input vs new sphinx input
```SQL
stopo_master=> select id, detail, label, origin, geom_st_box2d, num, egris_egrid, x, y, st_asewkt(the_geom) FROM vd.parzellen_sphinx  where egris_egrid = 'ch470171978501' limit 1;
-[ RECORD 1 ]-+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

change parcel data source

---

conf/uvek.conf.part

Layer IVS nat  and Ivs nat Verlaeufe has her proper table (it's a view of table ivs_nat with restriction on ivs_signature attribute).
Tooltip was already setting for using the view. Sphinx is now set too.

IVS must use views (with restrictions) for the search

---

conf/uvek.conf.part

The layer ch.bfe.energiestaedte-2000watt-aufdemweg is fully removed. 
The table bfe.energiestaedte_aufdemweg_2000watt will be removed after the deploy of 05.06

Remove energiestaedte-2000watt-aufdemweg

---

conf/search.conf.part

this will fix the lack of translated river and lake names in the swissearch index
related to https://github.com/geoadmin/service-sphinxsearch/issues/405
regression has been introduced with this https://github.com/geoadmin/mf-geoadmin3/issues/3941
[Testlink](https://mf-chsdi3.dev.bgdi.ch/shorten/8601c35bbc)
search for:
```
Silsersee
Langensee
Vierwaldstättersee
Genfersee
```

index multiple results with same feature_id (uuid) but different detail

---

conf/bafu.conf.part
conf/bod.conf.part
conf/dritte.conf.part
conf/kogis.conf.part
conf/lubis.conf.part
conf/search.conf.part
conf/stopo.conf.part
conf/uvek.conf.part
conf/vbs.conf.part

this pr will replace
```SQL
text1 || ' ' || integer1::text
``` 
with
```SQL
concat_ws(' ', text1, integer1)
```
in all the sphinx queries. The **concat_ws** function is variadic and **ignores null values**, type casting is not necessary.
With this pr, our sphinx queries will be clean. we should try to avoid the usage of ``text || integer::text`` for text concatenation in the future.

remove coalesce

---

conf/db.conf.in

since we we wont wait for any replication lags anymore on rds, we will build the sphinx index with the master database.

build sphinx indexes from master instance

---

buildspec.yml

By default the commands in buildspec are executed in `sh` we need to
specify the `shell: bash` tag to use bash. Bash allow us to use `[[` if
syntax.

Fixing Codebuild docker push

---

dev.env
int.env
prod.env
scripts/index-sync-rotate.sh

the list of valid prefixes will be extracted from sphinx config and has
rsync include-from format:
index_a.*
index_b.*

rsync will only sync files with valid sphinx config prefix

---

Makefile
scripts/pg2sphinx.sh

for index maintenance triggered by database and table deploys
* remove locking
since the sphinx index creation is writing into a filesystem it is not
necessary to have a locking mechanism.
the triggering database deploy itself is already locked, multiple
processes writing into same database are not allowed
* multiple maintenance container/jobs can run at the same time, the
container naming has to be extended with a random part (ppid)
the database deploy trigger will be changed here: https://github.com/geoadmin/deploy/pull/53

BGDIINF_SB-2216: tweaks and optimizations

---

Makefile
scripts/pg2sphinx.sh

the pg2pshinx endpoint, triggered by database/table deploy script will:
* not start and use local builds anymore
* only use ecr images (built by codebuild) and always check for newer images on ecr.
* the current image tag for dev/int/prod tag is detected by the database deploy script https://github.com/geoadmin/deploy/pull/53
we have to assure to always use the latest image, p.e  stable image names like develop-docker.latest or develop.latest, etc.

BGDIINF_SB-2216: pg2spshinx endpoint adaption for table deploy (automata and manual)

---

scripts/pg2sphinx.sh

the content of ~/.docker/config.json can be misleading because the token
is only valid for 12 hours.
after 12 hours the content of ~/.docker/config.json still contains the
credentials but a docker pull fails with this error:
docker: Error response from daemon: pull access denied
Your authorization token has expired. Reauthenticate and try again.

BGDIINF_SB-2216: improve the validation of the ecr token

---

Dockerfile
scripts/index-sync-rotate.sh

the current production is suffering regular outages due to the sync of indexes into the docker volume under load.
this pr tries to improve the stability of this sync process with some major changes in the workflow.
the new sync script is running on the two prod search hosts since 18.08.2022 15:00
there were no more crashes since then.

BGDIINF_SB-2549: improve stability of index sync and rotation

---

Dockerfile
scripts/index-sync-rotate.sh

* rsync is only started if searchd is running and accepting connections
* only fully updated indexes from EFS are synced into docker volume
* sync is started for each index in a for loop this should avoid
inconsistencies between the script metadata and the filesystem
need to apply the same fix https://github.com/geoadmin/service-sphinxsearch/pull/511 in the master branch for sphinx int and prod

BGDIINF_SB-2549:a few major changes in the rsync process

---

Dockerfile
scripts/checker.sh

this is a first draft of a container liveness probe (checker.sh) for service-sphinxsearch which can be used as healtcheck with docker and docker-compose.
The check assumes that `searchd --status` exit code represents the liveness of the search container. once the searchd daemon is running, the container is supposed to be alive.

BGDIINF_SB-2530: service sphinxsearch liveness probe

---

buildspec.yml

On CI manual build the CODEBUILD_WEBHOOK_HEAD_REF is not set !

BGDIINF_SB-2353: Fixing CI manual build

---

scripts/docker-cmd.sh

not yet present in the efs.
This auto-create will fail during deploy because new sphinx config will
be deployed before the database deploy.

fix docker-cmd script, do not create index on container start which are

---

scripts/pg2sphinx_trigger.py

during a table deploy/scan, all the queries in the sphinx config of the current database are being executed with explain analzye. The result of this analyze  is used to detect indexes that have to be updated, indexes that rely on the table that has been deployed.
with this change the pg2sphinx trigger will continue its scan if one of. the sphinx queries is invalid. this can happen during deploy days when new configs/images are already activated but the database has not yet been deployed. until now this scenario has not been catched by the except block because it is a `ProgrammingError`.

fix table scan behaviour

---

scripts/index-sync-rotate.sh

* send sighup / rotate after each index
* add a global lock on efs, multiple hosts are updated sequentially
* do not overwrite files used by searchd, this will cause unpredictable crashes during the sync. sync the new indexes into `*.new.sp*` files besides the original indexes. searchd will manage the files with the SIGHUP triggered rotation
with this fix, the container restarts, triggered by index updates under load that we are observing now on dev int and prod should stop.
the issue can be reproduced by hitting on the index while updating it:
```bash
# herdenschutzhunde
[ 28233 - 2022-09-13 07:16:42] -> 2022-09-13 07:16:42 start
[ 28233 - 2022-09-13 07:16:42] -> 2022-09-13 07:16:42 start sync: ch_bafu_alpweiden_herdenschutzhunde ...
sending incremental file list
./ …
```

BGDIINF_SB-2587: improvements in stability

---

Dockerfile
scripts/docker-cmd.sh
scripts/docker-crontab
scripts/index-sync-rotate.sh

make the logs searchd.log and query.log visible in the stdout of the docker main process pid=1 `/proc/1/fd/1` . with this modification these logs will be visible in docker logs.
truncate the searchd logs in the container each night

BGDIINF_SB-2562: make the logs searchd.log and query.log visible

---

scripts/index-sync-rotate.sh

without the dot in the -name parameter the address_metaphone* indexes
have been synced and rotated together with the address index.
```bash
sphinx_index=address
# before the fix
$ ls ${sphinx_index}*
address.spa  address.sph  address.spl  address.sps            address_metaphone.spe  address_metaphone.spk  address_metaphone.spp   address_metaphone.tmp1
address.spd  address.spi  address.spm  address_metaphone.spa  address_metaphone.sph  address_metaphone.spl  address_metaphone.sps   address_metaphone.tmp7
address.spe  address.spk  address.spp  address_metaphone.spd  address_metaphone.spi  address_metaphone.spm  address_metaphone.tmp0  address_metaphone.tmps
# after the fix
$ ls ${sphinx_index}.*
address.spa  address.spd  address.spe  address.sph  address.spi  address.spk  address.spl …
```

Fix address rotation issue

---

scripts/index-sync-rotate.sh

- fixes https://github.com/geoadmin/service-sphinxsearch/issues/539
- fixes permanent lock when index update is happening between efs index ready check and copy efs->docker volume (https://jira.swisstopo.ch/browse/BGDIDIC-1457)
```
WARNING: rotating index 'layers_fr': prealloc: failed to load /var/lib/sphinxsearch/data/index/layers_fr.new.spi: bad size 0 (at least 1 bytes expected); using old index
```
- removes global lock file, since the rotation of the indexes is now working stable we can sync them into the vhosts at the same time.

improvements in the stability of the index rotation script

---

conf/lubis.conf.part

the column ort will disappear with the migration to stac datasource

BGDIDIC-643: update label

---

scripts/docker-cmd.sh
scripts/pg2sphinx.sh

service container in the infra vhost environment. After a scan for orphaned indexes the container (running in service mode) tried to remove orphaned indexes on EFS which was mounted read-only on the host.
in service mode (as backend for search wsgi)
the service-sphinxsearch container needs read-only access to the EFS
in maintenance mode (triggered by data deploy on geodatasync) the service-sphinxsearch container needs read-write access to the EFS
with this change the clean-up of orphaned indexes in the EFS will be done only in maintenance mode, during the sphinx index createion.
this will allow us to strictly mount the geodata efs in read-only mode on all our kubernetes or infra vhosts instances.

this will fix an issue that has ocurred during the initial start of the

---

conf/stopo.conf.part

activate all year from 1850 - 2024 to return results when querying and
not only from the most recent year.
number_of_communes * num_of_years = 2200 * (2024-1850) ~= 430K entries
https://sys-api3.dev.bgdi.ch/rest/services/ech/SearchServer?sr=2056&searchText=bern&lang=de&type=featuresearch&features=ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill&timeEnabled=true&timeStamps=2024

swissboundaries3d-gemeinden: Even though there are going to be created a large index, this pr will

---

Dockerfile
scripts/docker-cmd.sh
scripts/docker-crontab
scripts/index-sync-rotate.sh

a few changes in the dockerfile and in the efs sync script are needed during the parallel operations of service-search-sphinx on infra-vhost and k8s.
on k8s we are forced to mount the efs indexes with the full path: so this will be the folder with the efs index files:
* `/var/local/geodata/service-sphinxsearch/${DBSTAGING}/index` 
this is due to a limitation of the aws efs csi driver which is not supporting subpaths as volumemount config. we would have to create new peristant volumes with terraform which is unreasonable for this special use-case.

PB-82: prepare migration to k8s

---

conf/uvek.conf.part

the hardcoded dev staging in the database name meant that the index has never been created on int and prod.

fix uvek.conf.part

---

conf/lubis.conf.part

Due to the migration of ch.swisstopo.lubis-luftbilder_farbe to stac the sphinx search index did not contain the old ebkey anymore. 
this fix will add the old ebkey to the index as legacy measure.

fix failing e2e tests on feature search

---

scripts/checker.sh

service is considered as healthy if
* searchd is running
* index sync is running and the index files are up-to-date

improve readiness probe

---

scripts/docker-cmd.sh

the custom fifo /tmp/stdout needs a first input here so that the index sync cronjob is starting correctly. The initial output ensures cron job logs are captured in each pod, even when multiple pods are running.

fix flaky cron start when running multiple pods in parallel

---

scripts/checker.sh

under certain circumstances the cron service is in an unstable state after the initial load. in this case it is sufficient to reload the crontab configuration.

make sure that the index update service is running. 

---

Dockerfile
scripts/docker-cmd.sh
scripts/index-sync-rotate.sh

these changes were needed during the parallel operation vhost/k8s
the new runtime is k8s and we dont need the infra-vhost mountpoints anymore

PB-81: post prod deploy clean-up

---

conf/lubis.conf.part
conf/search.conf.part

for fuzzy search requests we will set:
* enable_wildcards = 1
* wordforms = /dev/null
wordforms do not make sense with metaphone morphology. if wordforms are applied on a keyword, the metaphone code won't be build
with the improved fuzzy search in the wsgi app, the keywords will not be prefixed and suffixed with wildcards. we can enable wildcard expansion on all meptahone / fuzzy search indexes

PB-1167: improve fuzzy search index configuration

---

Makefile
scripts/pg2sphinx.sh

the limit will be set per docker run --memory parameter, by default 50% of the currently available memory can be used for the index creation.

limit the available memory for the sphinx index creation

---

Makefile

as decided with @ltrea we will only enable global cgroup limitations in a first step. if this is working fine a docker run limit is not necessary.

disable docker run memory limitation

---

scripts/checker.sh

some improvements in the sphinxsearch readiness probe:
- Ensure `searchd` is running before proceeding.
- Verify the existence and freshness of the index sync status file.
- Introduce `MAX_AGE` env variable with a default value of 300 seconds to determine the maximum allowable age for the index sync status file.
- Prevent further tests if `index-sync-rotate.sh` is currently running by checking for the presence of a lock file.
the check for the precence of a lock file will prevent false positives in the future. some sync commands can take up to 10-15 minutes if bigger indexes have been updated in the source EFS. during that time the readiness probe has been reporting false positive alerts before.

improve readiness check for searchd and index freshness

---

.github/workflows/milestone-version.yml

Now we tag also develop-* branch releases with YYYY-DD-MM-betaX tag.

PB-1537: Trigger milestone tagging on develop-*

---

conf/bafu.conf.part

I hope this is correct. It has been a while since I last configured a sphinx index ;-)

BGDIDIC-2043 add index for jb bundesinv.
